apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: nodeapp  
    spec:     # pod spec                  
      containers: 
      - name: node-app 
        image: image-registry.openshift-image-registry.svc:5000/usman/myis:v1
        ports:
        - containerPort: 3000
